=== LoyolaChicagoCode/betterxml.python/examples/MailMatch/matching.dtd
<?xml version="1.0" encoding="iso-8859-1"?>
<!ELEMENT Rule (To|From|Subject|And|Or)>

<!ELEMENT To EMPTY>
<!ATTLIST To match CDATA #REQUIRED>

<!ELEMENT From EMPTY>
<!ATTLIST From match CDATA #REQUIRED>

<!ELEMENT Subject EMPTY>
<!ATTLIST Subject match CDATA #REQUIRED>

<!ELEMENT And ( (To|From|Subject|And|Or)+ )>
<!ELEMENT Or ( (To|From|Subject|And|Or)+ )>

=== LoyolaChicagoCode/betterxml.python/bxml/examples/org/betterxml/xelement1/MailMatch/XML/rule_mixed2.xml
<?xml version="1.0"?>
<!DOCTYPE Rule SYSTEM "matching.dtd">
<Rule>
 <Or>
  <To match="gkt@cs.luc.edu"/>
  <And>
    <To match="pshafaee@hostway.com"/>
    <Or> 
      <Subject match="Hello World"/>
      <Subject match="Goodbye World"/>
    </Or>
  </And>  
 </Or>
</Rule>
